<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 4.1 (Python 3.9.7 on win32)" generated="20211003 14:07:27.976" rpa="false" schemaversion="2">
<suite id="s1" name="Test Dartboard" source="C:\Users\marsh\Documents\GitHub\499-Dart-Project\Testing\RobotScripts\test_dartboard.robot">
<test id="s1-t1" name="Test Dartboard">
<kw name="Navigate to Homepage">
<kw name="Open Browser">
<arg>${browser}</arg>
<msg timestamp="20211003 14:07:27.998" level="FAIL">No keyword with name 'Open Browser' found.</msg>
<status status="FAIL" starttime="20211003 14:07:27.998" endtime="20211003 14:07:27.998"/>
</kw>
<kw name="Go To">
<arg>${webpage}</arg>
<status status="NOT RUN" starttime="20211003 14:07:27.999" endtime="20211003 14:07:27.999"/>
</kw>
<status status="FAIL" starttime="20211003 14:07:27.997" endtime="20211003 14:07:27.999"/>
</kw>
<kw name="My Keyword">
<arg>C:\\Users\\marsh\\Documents\\GitHub\\499-Dart-Project\\Testing\\RobotScripts</arg>
<status status="NOT RUN" starttime="20211003 14:07:28.001" endtime="20211003 14:07:28.001"/>
</kw>
<status status="FAIL" starttime="20211003 14:07:27.996" endtime="20211003 14:07:28.001">No keyword with name 'Open Browser' found.</status>
</test>
<status status="FAIL" starttime="20211003 14:07:27.977" endtime="20211003 14:07:28.002"/>
</suite>
<statistics>
<total>
<stat pass="0" fail="1" skip="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" skip="0" id="s1" name="Test Dartboard">Test Dartboard</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20211003 14:07:27.994" level="ERROR">Error in file 'C:\Users\marsh\Documents\GitHub\499-Dart-Project\Testing\RobotScripts\test_dartboard.robot' on line 4: Importing library 'Selenium2library' failed: ModuleNotFoundError: No module named 'Selenium2library'
Traceback (most recent call last):
  None
PYTHONPATH:
  C:\Users\marsh\Documents\GitHub\499-Dart-Project\Testing\RobotScripts
  C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2032.0_x64__qbz5n2kfra8p0\python39.zip
  C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2032.0_x64__qbz5n2kfra8p0\DLLs
  C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2032.0_x64__qbz5n2kfra8p0\lib
  C:\Users\marsh\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0
  C:\Users\marsh\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages
  C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2032.0_x64__qbz5n2kfra8p0
  C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2032.0_x64__qbz5n2kfra8p0\lib\site-packages</msg>
</errors>
</robot>
